--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogedev/BetterBosses
build-by-default: true
branches:
- main
projects:
  BetterBosses:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.0
...
